### ISSUE TITLE
Why are there dependencies?

### ISSUE THREAD

**Issue by vikr01** [DesignRevision/shards-ui#45]
How is this package intended to be used with `node`?

From what I can tell, the javascript in `src` is being bundled into `dist` with `webpack` and since the `target` is `web` that means those dependencies will be bundled in as well -- which means they'd only need to be `devDependencies` so that the user doesn't need to install it when they install the package.

**Comment by hisk** [comment]
Hey @vikr01, 👋

Sorry for the delay! You are correct. Would you like to handle this one too? Thanks for your help so far, it's much appreciated! 😊

The only dependency left I guess should be just `bootstrap` since it's required by the main `scss` file only (as far as I remember) and it's not assumed to be installed. I'm not quite sure I understand what you mean with `node`, or that's what you were referring to?

**Comment by vikr01** [comment]
As far as I can see from the `dist` folder, there is no reference to `bootstrap` except in source maps. I don't think this project needs any dependencies at all.

**Comment by hisk** [comment]
_(sorry for the delay)_

@vikr01  Oh! I see what you mean now, and you're right. 😄 Some of the dependencies are redundant, except for Bootstrap which is used [here](https://github.com/DesignRevision/shards-ui/blob/master/src/scss/shards.scss#L9).

**Comment by vikr01** [comment]
@hisk That's the SCSS in `src`, seems that gets bundled into the CSS in `dist`.

**Comment by hisk** [comment]
@vikr01 You are correct, but removing `bootstrap` is assuming that everyone is using the compiled styles only. That would force some developers that prefer to have the flexibility of compiling the assets and overriding certain styles to manually install `bootstrap`, which is a bit counter-intuitive.
